<?php
/*
* $Id: xoops_version.php,v 1.1 2006/03/27 14:52:00 mikhail Exp $
* Module: WF-Quote
* Version: v1.00
* Release Date: 15 August 2005
* Author: hsalazar, after Catzwolf
* Licence: GNU
*/

$modversion['name'] = _MI_QUOTEMOD_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_QUOTEMOD_DESC;
$modversion['author'] = 'Catzwolf, Hsalazar';
$modversion['credits'] = 'Many thanks to Hsalazar, he is the man behind this one.';
//$modversion['help'] = "quotes.html";
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/quotes_slogo.png';
$modversion['dirname'] = 'wfquotes';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/category.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/quotes.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'quotecats';
$modversion['tables'][1] = 'quotes';
$modversion['tables'][2] = 'quotes_votedata';
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'quote_search';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_QUOTESUB_SMNAME1;
$modversion['sub'][1]['url'] = 'submit.php?op=add';

// Templates
$modversion['templates'][1]['file'] = 'quotes_category.html';
$modversion['templates'][1]['description'] = 'Display category';
$modversion['templates'][2]['file'] = 'quotes_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'quotes_quote.html';
$modversion['templates'][3]['description'] = 'Display quote';
$modversion['templates'][4]['file'] = 'quotes_ratefile.html';
$modversion['templates'][4]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = 'wfquote_block.php';
$modversion['blocks'][1]['name'] = _MI_QUOTE_BNAME1;
$modversion['blocks'][1]['description'] = 'Displays a random quote';
$modversion['blocks'][1]['show_func'] = 'b_show_quote';
$modversion['blocks'][1]['template'] = 'wfquote_block.html';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 't';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfquotes_com_approve';
$modversion['comments']['callback']['update'] = 'wfquotes_com_update';
